// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/accalina/restaurant-mgmt/app/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/accalina/restaurant-mgmt/app/model"
)

// FoodRepository is an autogenerated mock type for the FoodRepository type
type FoodRepository struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, filter
func (_m *FoodRepository) Count(ctx context.Context, filter *model.FoodFilter) int {
	ret := _m.Called(ctx, filter)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *model.FoodFilter) int); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// FetchAll provides a mock function with given fields: ctx, filter
func (_m *FoodRepository) FetchAll(ctx context.Context, filter *model.FoodFilter) ([]entity.Food, error) {
	ret := _m.Called(ctx, filter)

	var r0 []entity.Food
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.FoodFilter) ([]entity.Food, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.FoodFilter) []entity.Food); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Food)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.FoodFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, filter
func (_m *FoodRepository) Find(ctx context.Context, filter *model.FoodFilter) (*entity.Food, error) {
	ret := _m.Called(ctx, filter)

	var r0 *entity.Food
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.FoodFilter) (*entity.Food, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.FoodFilter) *entity.Food); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Food)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.FoodFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: tx, data
func (_m *FoodRepository) Save(tx *gorm.DB, data *entity.Food) (*entity.Food, error) {
	ret := _m.Called(tx, data)

	var r0 *entity.Food
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.Food) (*entity.Food, error)); ok {
		return rf(tx, data)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.Food) *entity.Food); ok {
		r0 = rf(tx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Food)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, *entity.Food) error); ok {
		r1 = rf(tx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFoodRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewFoodRepository creates a new instance of FoodRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFoodRepository(t mockConstructorTestingTNewFoodRepository) *FoodRepository {
	mock := &FoodRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
