// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/accalina/restaurant-mgmt/model"
	mock "github.com/stretchr/testify/mock"
)

// FoodService is an autogenerated mock type for the FoodService type
type FoodService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *FoodService) Create(ctx context.Context, _a1 model.FoodCreteOrUpdateModel) model.FoodCreteOrUpdateModel {
	ret := _m.Called(ctx, _a1)

	var r0 model.FoodCreteOrUpdateModel
	if rf, ok := ret.Get(0).(func(context.Context, model.FoodCreteOrUpdateModel) model.FoodCreteOrUpdateModel); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.FoodCreteOrUpdateModel)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *FoodService) Delete(ctx context.Context, id string) bool {
	ret := _m.Called(ctx, id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, queryParams
func (_m *FoodService) FindAll(ctx context.Context, queryParams *model.FoodFilter) ([]model.FoodModel, model.Meta, error) {
	ret := _m.Called(ctx, queryParams)

	var r0 []model.FoodModel
	var r1 model.Meta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.FoodFilter) ([]model.FoodModel, model.Meta, error)); ok {
		return rf(ctx, queryParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.FoodFilter) []model.FoodModel); ok {
		r0 = rf(ctx, queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoodModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.FoodFilter) model.Meta); ok {
		r1 = rf(ctx, queryParams)
	} else {
		r1 = ret.Get(1).(model.Meta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.FoodFilter) error); ok {
		r2 = rf(ctx, queryParams)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindById provides a mock function with given fields: ctx, id
func (_m *FoodService) FindById(ctx context.Context, id string) (model.FoodModel, error) {
	ret := _m.Called(ctx, id)

	var r0 model.FoodModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.FoodModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.FoodModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.FoodModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, foodModel, id
func (_m *FoodService) Update(ctx context.Context, foodModel model.FoodCreteOrUpdateModel, id string) model.FoodCreteOrUpdateModel {
	ret := _m.Called(ctx, foodModel, id)

	var r0 model.FoodCreteOrUpdateModel
	if rf, ok := ret.Get(0).(func(context.Context, model.FoodCreteOrUpdateModel, string) model.FoodCreteOrUpdateModel); ok {
		r0 = rf(ctx, foodModel, id)
	} else {
		r0 = ret.Get(0).(model.FoodCreteOrUpdateModel)
	}

	return r0
}

type mockConstructorTestingTNewFoodService interface {
	mock.TestingT
	Cleanup(func())
}

// NewFoodService creates a new instance of FoodService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFoodService(t mockConstructorTestingTNewFoodService) *FoodService {
	mock := &FoodService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
