// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HttpBinService is an autogenerated mock type for the HttpBinService type
type HttpBinService struct {
	mock.Mock
}

// PostMethod provides a mock function with given fields: ctx
func (_m *HttpBinService) PostMethod(ctx context.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewHttpBinService interface {
	mock.TestingT
	Cleanup(func())
}

// NewHttpBinService creates a new instance of HttpBinService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHttpBinService(t mockConstructorTestingTNewHttpBinService) *HttpBinService {
	mock := &HttpBinService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
