definitions:
  entity.Food:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      menu:
        $ref: '#/definitions/entity.Menu'
      menuID:
        type: string
      name:
        type: string
      price:
        type: integer
      qty:
        type: integer
      updatedAt:
        type: string
    type: object
  entity.Menu:
    properties:
      category:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      endDate:
        type: string
      foods:
        items:
          $ref: '#/definitions/entity.Food'
        type: array
      id:
        type: string
      name:
        type: string
      startDate:
        type: string
      updatedAt:
        type: string
    type: object
  model.FoodCreateOrUpdateSwaggerModel:
    properties:
      menuId:
        type: string
      name:
        minLength: 1
        type: string
      price:
        minimum: 1
        type: integer
      qty:
        minimum: 1
        type: integer
    required:
    - menuId
    - name
    - price
    - qty
    type: object
  model.GeneralResponse:
    properties:
      code:
        type: integer
      data: {}
      errors: {}
      message:
        type: string
      meta: {}
      success:
        type: boolean
    type: object
  model.MenuCreateOrUpdateSwaggerModel:
    properties:
      category:
        minLength: 1
        type: string
      endDate:
        type: string
      name:
        minLength: 1
        type: string
      startDate:
        type: string
    required:
    - category
    - endDate
    - name
    - startDate
    type: object
  model.ResponseLogin:
    properties:
      token:
        type: string
    type: object
  model.UserCreateModel:
    properties:
      password:
        minLength: 6
        type: string
      username:
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
info:
  contact:
    email: your@mail.com
    name: API Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: RESTAURANT-MGMT API
  version: "1.0"
paths:
  /food:
    get:
      consumes:
      - application/json
      description: List all food.
      parameters:
      - description: name search
        in: query
        name: search
        type: string
      - description: limit search
        in: query
        name: limit
        type: string
      - description: page search
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Food'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GeneralResponse'
      summary: List all food
      tags:
      - Food
    post:
      consumes:
      - application/json
      description: Create a new Food.
      parameters:
      - description: Food attribute
        in: body
        name: Food
        required: true
        schema:
          $ref: '#/definitions/model.FoodCreateOrUpdateSwaggerModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Food'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GeneralResponse'
      security:
      - ApiKeyAuth: []
      summary: create a new Food
      tags:
      - Food
  /food/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Food.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GeneralResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GeneralResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete Food
      tags:
      - Food
    get:
      consumes:
      - application/json
      description: List detail food.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Food'
      summary: List detail food
      tags:
      - Food
    put:
      consumes:
      - application/json
      description: Update Food.
      parameters:
      - description: Food attribute
        in: body
        name: Food
        required: true
        schema:
          $ref: '#/definitions/model.FoodCreateOrUpdateSwaggerModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Food'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GeneralResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Food
      tags:
      - Food
  /menu:
    get:
      consumes:
      - application/json
      description: List all menu.
      parameters:
      - description: name search
        in: query
        name: search
        type: string
      - description: limit search
        in: query
        name: limit
        type: string
      - description: page search
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Menu'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GeneralResponse'
      summary: List all menu
      tags:
      - Menu
    post:
      consumes:
      - application/json
      description: Create a new menu.
      parameters:
      - description: Menu attribute
        in: body
        name: Menu
        required: true
        schema:
          $ref: '#/definitions/model.MenuCreateOrUpdateSwaggerModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Menu'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GeneralResponse'
      security:
      - ApiKeyAuth: []
      summary: create a new menu
      tags:
      - Menu
  /menu/{id}:
    delete:
      consumes:
      - application/json
      description: Delete menu.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Menu'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GeneralResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete menu
      tags:
      - Menu
    get:
      consumes:
      - application/json
      description: Detail menu.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Menu'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GeneralResponse'
      summary: Detail menu
      tags:
      - Menu
    put:
      consumes:
      - application/json
      description: Update menu.
      parameters:
      - description: Menu attribute
        in: body
        name: Menu
        required: true
        schema:
          $ref: '#/definitions/model.MenuCreateOrUpdateSwaggerModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Menu'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GeneralResponse'
      security:
      - ApiKeyAuth: []
      summary: Update menu
      tags:
      - Menu
  /user/login:
    post:
      consumes:
      - application/json
      description: Create a new access token.
      parameters:
      - description: Login atributes
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/model.UserCreateModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseLogin'
      summary: create a new access token
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: Create a new User.
      parameters:
      - description: User attribute
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/model.UserCreateModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseLogin'
      security:
      - ApiKeyAuth: []
      summary: create a new User
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
